# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f26377415afbc4711085761ed6fdb91d426ff09182ff8275b45161879e152df757c067372d34a629871e5dc6c8507308eb84f671f953cdfb8dbe55340dbb0dd

test:
  secret_key_base: ae0130dcaa04f4b16ee05a0d0b7a7639c0edeeb216670204c57d78a46fa557d6e0267090ed808b72b59fe3ef17ac5bf30073a37b8455c4fad416d00e4e27ef0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
